// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAc19zhaiCNXR8Uoux4SVqbr4qlLliOIZQ',
    appId: '1:55383098639:web:65f1b60e6d8b01c0c1aa7a',
    messagingSenderId: '55383098639',
    projectId: 'chomi-sa-app',
    authDomain: 'chomi-sa-app.firebaseapp.com',
    storageBucket: 'chomi-sa-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVHhPxrJ15gx09z7Kul_Ba952FdZDsCrU',
    appId: '1:55383098639:ios:bfa4e8d40fa081f9c1aa7a',
    messagingSenderId: '55383098639',
    projectId: 'chomi-sa-app',
    storageBucket: 'chomi-sa-app.firebasestorage.app',
    iosBundleId: 'com.example.chomi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVHhPxrJ15gx09z7Kul_Ba952FdZDsCrU',
    appId: '1:55383098639:ios:bfa4e8d40fa081f9c1aa7a',
    messagingSenderId: '55383098639',
    projectId: 'chomi-sa-app',
    storageBucket: 'chomi-sa-app.firebasestorage.app',
    iosBundleId: 'com.example.chomi',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyyVHS3YHK8kyLgRC6Wxzcw40k3TEJemI',
    appId: '1:588365046744:android:c59feae02bc357267708ad',
    messagingSenderId: '588365046744',
    projectId: 'chomi-social',
    storageBucket: 'chomi-social.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnfFKPT3F0lZ0FqpfkmYDkX-qPg4WE6mc',
    appId: '1:588365046744:web:ed9b0f3d5c5984817708ad',
    messagingSenderId: '588365046744',
    projectId: 'chomi-social',
    authDomain: 'chomi-social.firebaseapp.com',
    storageBucket: 'chomi-social.firebasestorage.app',
  );

}